import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alonso
 */
public class panelPlaylist extends javax.swing.JPanel {

    private DefaultTableModel modeloTabla;
    private ListaPlaylist listaGlobal;
    private ColaReproduccion colaGlobal;
    
    /**
     * Creates new form panelPlaylist
     */
    public panelPlaylist() {
        initComponents();
        inicializarModelo();
        javax.swing.table.DefaultTableCellRenderer renderEncabezado = new javax.swing.table.DefaultTableCellRenderer();
        renderEncabezado.setBackground(new java.awt.Color(0, 51, 102)); // Fondo azul
        renderEncabezado.setForeground(java.awt.Color.WHITE);           // Letra blanca
        renderEncabezado.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        renderEncabezado.setHorizontalAlignment(javax.swing.JLabel.CENTER); // Centrar el texto

        // Aplicar diseño a cada columna
        for (int i = 0; i < tablaCanciones.getModel().getColumnCount(); i++) {
            tablaCanciones.getColumnModel().getColumn(i).setHeaderRenderer(renderEncabezado);
        }
        
        tablaCanciones.setBackground(new java.awt.Color(0, 51, 102));
        tablaCanciones.setForeground(java.awt.Color.WHITE);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(0, 51, 102));
        tablaCanciones.setGridColor(new java.awt.Color(100, 150, 200));
    }
    
    // Método para recibir los datos de la ventana principal
    public void configurarEstructuras(ListaPlaylist lista, ColaReproduccion cola) {
        this.listaGlobal = lista;
        this.colaGlobal = cola;
    }
    
    /**
     * Configura el modelo inicial de la tabla recuperando el diseño de NetBeans
     */
    private void inicializarModelo() {
        // Vincular el objeto al modelo que NetBeans creo por defecto
        modeloTabla = (DefaultTableModel) tablaCanciones.getModel();
    }
    
    /**
     * Metodo publico y modular para agregar canciones
     * @param titulo Nombre de la cancion
     * @param artista Nombre del interprete
     * @param rutaArchivo Ubicacion del archivo de audio
     */
    public void agregarCancionGraficamente(String titulo, String artista, String rutaArchivo) {
        // Creamos un arreglo de objetos con los datos de la fila
        Object[] nuevaFila = {titulo, artista, rutaArchivo};
        
        // El modelo inserta la fila y la tabla se actualiza visualmente de inmediato
        modeloTabla.addRow(nuevaFila);
    }
    
    /**
     * Limpia por completo las filas de la tabla
     */
    public void limpiarTabla() {
        modeloTabla.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCanciones = new javax.swing.JTable();
        btnAgregarCola = new javax.swing.JButton();
        btnDescargar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Playlist");

        jScrollPane1.setBackground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tablaCanciones.setBackground(new java.awt.Color(0, 51, 102));
        tablaCanciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaCanciones.setForeground(new java.awt.Color(255, 255, 255));
        tablaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Artista", "Archivo de Audio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCanciones);

        btnAgregarCola.setBackground(new java.awt.Color(102, 102, 102));
        btnAgregarCola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarCola.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCola.setText("Agregar a la Cola");
        btnAgregarCola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColaActionPerformed(evt);
            }
        });

        btnDescargar.setBackground(new java.awt.Color(102, 102, 102));
        btnDescargar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDescargar.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargar.setText("Descargar Cancion");
        btnDescargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDescargar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescargar)
                    .addComponent(btnAgregarCola))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColaActionPerformed
        // Obtener el número de fila que el usuario sombreó con el ratón
        int filaSeleccionada = tablaCanciones.getSelectedRow();

        // Si el valor es -1, significa que no hay nada seleccionado
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una canción de la tabla primero.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extraer el texto de la columna 0 (El titulo)
        String tituloSeleccionado = tablaCanciones.getValueAt(filaSeleccionada, 0).toString();

        // El motor de búsqueda hace su trabajo en la memoria
        Cancion cancionEncontrada = listaGlobal.buscarPorTitulo(tituloSeleccionado);

        if (cancionEncontrada != null) {
            // Clonar los datos hacia la cola de espera
            colaGlobal.encolar(cancionEncontrada.getTitulo(), cancionEncontrada.getArtista(), 
                               cancionEncontrada.getRutaAudio(), cancionEncontrada.getRutaImagen());
                               
            javax.swing.JOptionPane.showMessageDialog(this, "Canción agregada a la cola exitosamente.");
        }
    }//GEN-LAST:event_btnAgregarColaActionPerformed

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
        // Obtener la fila seleccionada por el usuario
        int filaSeleccionada = tablaCanciones.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una canción de la tabla para descargar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Recuperar el título de la columna 0 y buscar el nodo en la Lista Doble
        String tituloSeleccionado = tablaCanciones.getValueAt(filaSeleccionada, 0).toString();
        Cancion cancionEncontrada = listaGlobal.buscarPorTitulo(tituloSeleccionado);

        if (cancionEncontrada != null) {
            java.io.File archivoOrigen = new java.io.File(cancionEncontrada.getRutaAudio());

            // Verificación física de que el archivo WAV de origen exista en el proyecto
            if (!archivoOrigen.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El archivo de origen no se encuentra en los recursos del sistema.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Configura el selector de archivos en modo de guardado
            javax.swing.JFileChooser guardador = new javax.swing.JFileChooser();
            guardador.setDialogTitle("Descargar Canción");
            guardador.setSelectedFile(new java.io.File(cancionEncontrada.getTitulo() + ".wav"));

            int resultado = guardador.showSaveDialog(this);

            // Si el usuario confirma la ruta y presiona Guardar, duplicamos los bytes
            if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File archivoDestino = guardador.getSelectedFile();
                try {
                    java.nio.file.Files.copy(
                        archivoOrigen.toPath(), 
                        archivoDestino.toPath(), 
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING
                    );
                    javax.swing.JOptionPane.showMessageDialog(this, "La canción se ha descargado exitosamente.");
                } catch (java.io.IOException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar copiar el archivo al directorio destino.", "Error de Descarga", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDescargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCola;
    private javax.swing.JButton btnDescargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCanciones;
    // End of variables declaration//GEN-END:variables
}
