
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alonso
 */
public class panelCola extends javax.swing.JPanel {
    
    private DefaultTableModel modeloTablaCola;
    private ColaReproduccion colaGlobal;

    /**
     * Creates new form panelCola
     */
    public panelCola() {
        initComponents();
        inicializarModeloCola();
        estilizarEncabezado();
    }
    
    /**
     * Configura el modelo para soportar imágenes y ajusta el tamaño de las celdas
     */
    private void inicializarModeloCola() {
        // Reemplaza el modelo por defecto por uno que reconozca imágenes
        modeloTablaCola = new DefaultTableModel(
            new Object [][] {},
            new String [] {"Imagen", "Título", "Artista"}
        ) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Indicar a Java que la primera columna (0) contiene una Imagen
                if (columnIndex == 0) {
                    return ImageIcon.class; 
                }
                return String.class;
            }
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false; // Ninguna celda se puede editar
            }
        };
        
        tablaCola.setModel(modeloTablaCola);
        
        // Hacer las filas más anchas para que la portada se vea bien
        tablaCola.setRowHeight(60); 
    }
    
    private void estilizarEncabezado() {
        javax.swing.table.DefaultTableCellRenderer renderEncabezado = new javax.swing.table.DefaultTableCellRenderer();
        renderEncabezado.setBackground(new java.awt.Color(0, 51, 102));
        renderEncabezado.setForeground(java.awt.Color.WHITE);
        renderEncabezado.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        renderEncabezado.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        for (int i = 0; i < tablaCola.getModel().getColumnCount(); i++) {
            tablaCola.getColumnModel().getColumn(i).setHeaderRenderer(renderEncabezado);
        }
        
        tablaCola.setBackground(new java.awt.Color(0, 51, 102));
        tablaCola.setForeground(java.awt.Color.WHITE);
        jScrollPane2.getViewport().setBackground(new java.awt.Color(0, 51, 102));
    }

    /**
     * Sincroniza los componentes visuales del panel.
     * Ya no necesitamos pasar cancionActual, solo llenamos la tabla.
     */
    public void actualizarPanel(ColaReproduccion cola) {
        this.colaGlobal = cola;
        // Limpiar filas previas
        modeloTablaCola.setRowCount(0);
        
        Cancion actualCola = cola.getFrente();
        while (actualCola != null) {
            ImageIcon miniatura = null;
            
            // Procesamos la imagen para hacerla miniatura (50x50)
            java.io.File archivoImagen = new java.io.File(actualCola.getRutaImagen());
            if (archivoImagen.exists()) {
                ImageIcon iconoOriginal = new ImageIcon(actualCola.getRutaImagen());
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
                miniatura = new ImageIcon(imagenEscalada);
            }
            
            // Insertamos la miniatura junto al texto
            Object[] fila = {miniatura, actualCola.getTitulo(), actualCola.getArtista()};
            modeloTablaCola.addRow(fila);
            
            actualCola = actualCola.getSiguiente();
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCola = new javax.swing.JTable();
        btnQuitarCola = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 102));

        jScrollPane2.setBackground(new java.awt.Color(0, 51, 102));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tablaCola.setBackground(new java.awt.Color(0, 51, 102));
        tablaCola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaCola.setForeground(new java.awt.Color(255, 255, 255));
        tablaCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Imagen", "Titulo", "Artista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCola);

        btnQuitarCola.setBackground(new java.awt.Color(204, 0, 51));
        btnQuitarCola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuitarCola.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitarCola.setText("Quitar de la cola");
        btnQuitarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarColaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitarCola)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnQuitarCola)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarColaActionPerformed
        // Obtener el índice de la fila que el usuario seleccionó
        int filaSeleccionada = tablaCola.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una canción de la tabla para quitarla.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extraer el texto del título
        String tituloSeleccionado = tablaCola.getValueAt(filaSeleccionada, 1).toString();

        // Ejecutar la desconexión de apuntadores en la memoria RAM
        boolean exito = colaGlobal.eliminarPorTitulo(tituloSeleccionado);

        if (exito) {
            // Refresca la interfaz visual pasándole la cola ya modificada
            actualizarPanel(colaGlobal);
        }
    }//GEN-LAST:event_btnQuitarColaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitarCola;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCola;
    // End of variables declaration//GEN-END:variables
}
