
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alonso
 */
public class colas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(colas.class.getName());

    String[] cola;
    int capacidad, frente = -1, fin = 0, contador = 0;
    
    /**
     * Creates new form pilas
     */
    public colas() {
        try{
            capacidad = Integer.parseInt(JOptionPane.showInputDialog("Escribe la capacidad del arreglo: "));
            cola = new String[capacidad]; //Instanciar la pila con la capacidad definida por el usuario
            initComponents();
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null,"Error. Vuelve a intentarlo");
//            System.out.println("Error. Vuelve a intentarlo");
        }
    }
    
    void insertar(){
        if(contador==capacidad){
            JOptionPane.showMessageDialog(null, "La Cola ya no tiene capacidad");
        } else{
            cola[fin] = JOptionPane.showInputDialog("Escribe un nombre: ");
            if(fin==capacidad-1){
                fin=0;
            }else{
                fin++;
            }
            contador++;
            if (frente==-1){
                frente=0;
            }
        }
    }
    
    void Eliminar() {
        if (!vacia()) {
            cola[frente] = null;
            frente++;

            if (frente == capacidad) {
                frente = 0;
            }

            contador--;
        } else {
            JCola.append("No hay elementos en la Cola");
        }
    }
     
    public void verCola(){
        JCola.setText("");
        if(!vacia()){
            int i = frente;
            
            for(int c = 0;c < contador;c++){
                JCola.append(cola[i]+"\n");
                i++;
                if(i==capacidad){
                    i=0;
                }
            }
        }else{
            JCola.append("No hay elementos en la Cola");
        }
    
    }
    
    public boolean vacia(){
        return contador == 0;
    }
    
    public boolean llena(){
        return contador==capacidad;
    }
    
    public void verNumElem(){
        JCola.setText("");
        JCola.append("Numero de elementos: "+contador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnPop = new javax.swing.JButton();
        BtnPush = new javax.swing.JButton();
        BtnLlena = new javax.swing.JButton();
        BtnEmpty = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JCola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        BtnPop.setBackground(new java.awt.Color(255, 204, 204));
        BtnPop.setText("Eliminar");
        BtnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPopActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPop);

        BtnPush.setBackground(new java.awt.Color(204, 255, 204));
        BtnPush.setText("Insertar");
        BtnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPushActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPush);

        BtnLlena.setBackground(new java.awt.Color(204, 204, 255));
        BtnLlena.setText("Llena");
        BtnLlena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLlenaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLlena);

        BtnEmpty.setBackground(new java.awt.Color(204, 204, 255));
        BtnEmpty.setText("Vacia");
        BtnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmptyActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEmpty);

        JCola.setEditable(false);
        JCola.setBackground(new java.awt.Color(219, 246, 245));
        JCola.setColumns(20);
        JCola.setRows(5);
        JCola.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(JCola);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1.setText("Cola");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPopActionPerformed
        Eliminar();
        verCola();
    }//GEN-LAST:event_BtnPopActionPerformed

    private void BtnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPushActionPerformed
        insertar();
        verCola();
    }//GEN-LAST:event_BtnPushActionPerformed

    private void BtnLlenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLlenaActionPerformed
        JCola.setText("");
        if(llena()){
            JCola.append("La cola esta llena");
        } else {
            JCola.append("La cola no esta llena");
        }
    }//GEN-LAST:event_BtnLlenaActionPerformed

    private void BtnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmptyActionPerformed
        JCola.setText("");
        if(vacia()){
            JCola.append("No hay elementos en la Cola");
        } else{
            JCola.append("La Cola si tiene elementos");
        }
    }//GEN-LAST:event_BtnEmptyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new colas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEmpty;
    private javax.swing.JButton BtnLlena;
    private javax.swing.JButton BtnPop;
    private javax.swing.JButton BtnPush;
    private javax.swing.JTextArea JCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
