
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alonso
 */
public class pilas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pilas.class.getName());

    String Pila[];
    int capacidad, tope = 0;
    
    /**
     * Creates new form pilas
     */
    public pilas() {
        try{
            capacidad = Integer.parseInt(JOptionPane.showInputDialog("Escribe la capacidad del arreglo: "));
            Pila = new String[capacidad]; //Instanciar la pila con la capacidad definida por el usuario
        }catch( Exception e ){
            JOptionPane.showMessageDialog(null,"Error. Vuelve a intentarlo");
//            System.out.println("Error. Vuelve a intentarlo");
        }
        initComponents();
    }
    void pop (){
        
        if(vacia()==false){
            Pila[tope-1]="";
            tope--;
        } else {
            JPila.append("No hay elementos en la Pila");
        }
    
    }
    
    void push (){
    
        if(tope<capacidad){
            Pila[tope] = JOptionPane.showInputDialog("Escribe un nombre: ");
            tope++;
        } else {
            JOptionPane.showMessageDialog(null, "La pila ya no tiene capacidad");
        
        }
    
    }
    public void verPila(){
        JPila.setText("");
        if(vacia()==false){
            for( int i=tope-1; i>=0 ; i--){
                JPila.append(Pila[i]+"\n");
            }
        } else{
            JPila.append("No hay elementos en la Pila");
        }
    }
    
    public void verTop(){
        JPila.setText("");
        if(vacia()==false){
            JPila.append(Pila[tope-1]);
        } else{
            JPila.append("No hay elementos en la Pila");
        }
    }
    
    public boolean vacia(){
        return tope==0;
    }
    
    public void verNumElem(){
        JPila.setText("");
        JPila.append("Numero de elementos: "+tope);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnPop = new javax.swing.JButton();
        BtnPush = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPila = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        BtnPop.setBackground(new java.awt.Color(255, 204, 204));
        BtnPop.setText("Pop");
        BtnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPopActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPop);

        BtnPush.setBackground(new java.awt.Color(204, 255, 204));
        BtnPush.setText("Push");
        BtnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPushActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPush);

        JPila.setEditable(false);
        JPila.setBackground(new java.awt.Color(219, 246, 245));
        JPila.setColumns(20);
        JPila.setRows(5);
        JPila.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(JPila);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1.setText("Pila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPopActionPerformed
        pop();
        verPila();
    }//GEN-LAST:event_BtnPopActionPerformed

    private void BtnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPushActionPerformed
        push();
        verPila();
    }//GEN-LAST:event_BtnPushActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pilas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPop;
    private javax.swing.JButton BtnPush;
    private javax.swing.JTextArea JPila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
