
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alonso
 */
public class ListaEnlazada extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaEnlazada.class.getName());
    
    Nodo frente=null, Final=null, aux=null;
    Nodo nuevo;
    
    void insertar(int x){
        
        nuevo = new Nodo(x,null); //Crea una nueva instancia de un nodo
        
        if (Final!=null){
            //Cuando ya hay elementos en la lista
            Final.setSiguiente(nuevo);
            Final=nuevo;
            
        } else{//Cuando es el primer elemento que se va a inserta
            Final=nuevo; 
            frente=nuevo;
            //Como solo hay un elemento, el final y el frente quedan en ese elemento
        }
        labDato.setText(String.valueOf(Final.getInfo())); //Muestra el dato del nuevo nodo
        labPuntero.setText(String.valueOf(Final)); //Muestra el puntero
    }

    void MostrarLista(){
        aux=frente;
        int cont=1;
        if(Final==null){
            JOptionPane.showConfirmDialog(null, "Lista vacia");
        } else{
            while(aux!=null){
                System.out.println(cont+"_"+aux.getInfo()+" Direccion: "+ aux.getSiguiente());
                aux=aux.getSiguiente();
                cont++;
            }
        } 
    }
    
    void eliminarFrente(){
        if(frente==null && Final==null){ //Verificar si la lista tiene elementos
            JOptionPane.showMessageDialog(null,"Lista vacia");
        } else {
            JOptionPane.showMessageDialog(null,"Elemento a borrar:"+frente.info);//Muestra informacion del nodo a eliminar
            frente=frente.getSiguiente(); //Mueve el apuntador frente al proximo elemento
            if(frente==null){
                Final=null;
            }
            JOptionPane.showMessageDialog(null,"Elemento eliminado");
        }
    }
    
    void eliminarFinal(){
        aux=frente;
        if(frente==null && Final==null){
            JOptionPane.showMessageDialog(null,"Lista vacia");
        } else{
            if(frente==Final){
                JOptionPane.showMessageDialog(null,"Elemento Eliminado:"+aux.info);
                Final.setSiguiente(null);
                frente.setSiguiente(null);
            }else{
                while(aux.Siguiente.Siguiente!=null){
                    aux=aux.getSiguiente();
                }
                JOptionPane.showMessageDialog(null,"Elemento Eliminado:"+aux.Siguiente.info);
                Final=aux;
                Final.setSiguiente(null);
            }
        }
    }
    
    void EliminarX(int x){
        aux=frente;
        Nodo aux2;
        if(frente==null && Final==null){
            JOptionPane.showMessageDialog(null,"Lista vacia");
        }else{
            if(frente==Final){
                if(frente.info!=x){
                    JOptionPane.showMessageDialog(null,"Elemento '"+x+"' no existe");
                }else{
                    JOptionPane.showMessageDialog(null,"Elemento Eliminado:"+aux.info);
                    Final.setSiguiente(null);
                    frente.setSiguiente(null);
                }
            }else{
                while(aux.Siguiente.info!=x){
                    aux=aux.getSiguiente();
                }
                aux2=aux.Siguiente.Siguiente;
                JOptionPane.showMessageDialog(null,"Elemento Eliminado:"+aux.Siguiente.info);
                aux.Siguiente.setSiguiente(null);
                aux.setSiguiente(aux2);
            }
        }
    }
    
    public ListaEnlazada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnBorrarFrente = new javax.swing.JButton();
        btnBorrarFinal = new javax.swing.JButton();
        btnBorrarX = new javax.swing.JButton();
        labDato = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        labPuntero = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Listas Enlazadas");

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        btnInsertar.setBackground(new java.awt.Color(204, 255, 204));
        btnInsertar.setText("Insertar");
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar);

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSiguiente);

        btnBorrarFrente.setBackground(new java.awt.Color(255, 204, 204));
        btnBorrarFrente.setText("Borrar Frente");
        btnBorrarFrente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarFrenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarFrente);

        btnBorrarFinal.setBackground(new java.awt.Color(255, 204, 204));
        btnBorrarFinal.setText("Borrar Final");
        btnBorrarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarFinalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarFinal);

        btnBorrarX.setText("Borrar X");
        btnBorrarX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarXActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarX);

        labDato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labDato.setText("NULL");

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 200, 0));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("<-");
        jButton4.setEnabled(false);
        jPanel2.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setText("->");
        jButton5.setEnabled(false);
        jPanel2.add(jButton5);

        labPuntero.setText("Puntero");

        btnMostrar.setBackground(new java.awt.Color(204, 255, 255));
        btnMostrar.setText("Mostrar todo");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labPuntero, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnMostrar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labDato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labPuntero)
                        .addGap(32, 32, 32)
                        .addComponent(btnMostrar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try{
            insertar(Integer.parseInt(JOptionPane.showInputDialog("Dame el elemento a insertar en la lista: ")));
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Error en el valor proporcionado");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        MostrarLista();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBorrarFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarFrenteActionPerformed
        eliminarFrente();
    }//GEN-LAST:event_btnBorrarFrenteActionPerformed

    private void btnBorrarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarFinalActionPerformed
        eliminarFinal();
    }//GEN-LAST:event_btnBorrarFinalActionPerformed

    private void btnBorrarXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarXActionPerformed
        try{
            EliminarX(Integer.parseInt(JOptionPane.showInputDialog("Elemento a eliminar: ")));
        } catch(HeadlessException | NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Error en el valor proporcionado");
        }
    }//GEN-LAST:event_btnBorrarXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListaEnlazada().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarFinal;
    private javax.swing.JButton btnBorrarFrente;
    private javax.swing.JButton btnBorrarX;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labDato;
    private javax.swing.JLabel labPuntero;
    // End of variables declaration//GEN-END:variables
}
