
import javax.swing.DefaultListModel;
import javax.swing.UIManager;

/**
 *
 * @author Alonso
 */
public class Historial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Historial.class.getName());
    DefaultListModel<String> modeloHistorial = new DefaultListModel<>();
    
    Nodo nuevo, Frente=null, Final=null, aux=null, actual;

    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
        listURL.setModel(modeloHistorial);
        txtUrl.requestFocus();
    }
    
    public void agregarUrl() {
        String url = txtUrl.getText();

        if (!url.isEmpty()) {
            nuevo = new Nodo(url);

            if (Frente == null) {
                Frente = nuevo;
                Final = nuevo;
                actual = nuevo;
            } else {
                // El nuevo apunta al antiguo Frente
                nuevo.setSiguiente(Frente);
                Frente.setAnterior(nuevo);

                // El nuevo se convierte en el Frente
                Frente = nuevo;
                actual = nuevo;
            }

            // Actualizar la visualizacion del historial :)
            modeloHistorial.add(0, " [ " + new java.util.Date() + " ] " + url);
            labActual.setText("Sitio actual: " + url);
            txtUrl.setText("");
            txtUrl.requestFocus();
        }
    }
    
    public void retroceder() {
        // Verificar si hay un sitio atrás
        if (actual != null && actual.getSiguiente() != null) {

            // Mover el puntero actual al siguiente nodo de la lista
            actual = actual.getSiguiente();

            // Actualizar la etiqueta visual
            labActual.setText("Sitio actual: " + actual.getURL());

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay más historial anterior.");
        }
    }
    
    public void avanzar() {
        // Verificar si hay un sitio atrás
        if (actual != null && actual.getAnterior() != null) {

            // Mover el puntero actual al nodo que queda antes en la lista
            actual = actual.getAnterior();

            // Actualizar la etiqueta visual
            labActual.setText("Sitio actual: " + actual.getURL());

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay más historial adelante.");
        }
    }
    
    public void borrarTodo() {
        // Preguntar por seguridad
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas eliminar todo el historial?",
                "Confirmar limpieza",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {

            // Al poner Frente y Final en null, se pierde la referencia a toda la cadena.
            // El recolector de basura de Java liberará la memoria.
            Frente = null;
            Final = null;
            actual = null;

            // Lógica Visual
            modeloHistorial.clear(); // Esto borra todo el JList de golpe
            labActual.setText("Sitio actual: [Vacío]");
            txtUrl.setText("");

            // Foco de vuelta al campo de texto
            txtUrl.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnIr = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listURL = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        labActual = new javax.swing.JLabel();
        btnBorrarHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(601, 50));

        jLabel1.setText("URL:");

        txtUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrlActionPerformed(evt);
            }
        });

        btnIr.setText("Ir");
        btnIr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtras.setText("←");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAvanzar.setText("→");
        btnAvanzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnIr)
                    .addComponent(btnAvanzar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        listURL.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(listURL);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(50, 50, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 60));

        labActual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labActual.setForeground(new java.awt.Color(255, 255, 255));
        labActual.setText("Sitio actual: Esperando...");

        btnBorrarHistorial.setBackground(new java.awt.Color(50, 50, 50));
        btnBorrarHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBorrarHistorial.setForeground(new java.awt.Color(255, 51, 51));
        btnBorrarHistorial.setText("Borrar Historial");
        btnBorrarHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labActual)
                    .addComponent(btnBorrarHistorial))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarHistorial)
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        agregarUrl();
    }//GEN-LAST:event_txtUrlActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        agregarUrl();
    }//GEN-LAST:event_btnIrActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        retroceder();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        avanzar();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnBorrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarHistorialActionPerformed
        borrarTodo();
    }//GEN-LAST:event_btnBorrarHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Historial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnBorrarHistorial;
    private javax.swing.JButton btnIr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labActual;
    private javax.swing.JList<String> listURL;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
