import javax.swing.JOptionPane;

/**
 *
 * @author Alonso
 */
public class pilas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pilas.class.getName());

    String Pila[];
    int tope = 0;
    
    /**
     * Creates new form pilas
     */
    public pilas() {
        Pila = new String[10];
        initComponents();
    }
    void pop() {
        if (!vacia()) {
            Pila[tope - 1] = "";
            tope--;
        } else {
            JOptionPane.showMessageDialog(null, "No hay acciones para deshacer.");
        }
    }
    
    void push (String accion){
    
        if(tope<10){
            Pila[tope] = accion;
            tope++;
        } else {
            JOptionPane.showMessageDialog(null, "La pila ya no tiene capacidad");
        
        }
    
    }
    public void verPila(){
        JPila.setText("");
        if(vacia()==false){
            for( int i=tope-1; i>=0 ; i--){
                JPila.append(Pila[i]+"\n");
            }
        } else{
            JPila.append("No hay elementos en la Pila");
        }
    }
    
    public boolean vacia(){
        return tope==0;
    }
    
    public void verNumElem(){
        JPila.setText("");
        JPila.append("Numero de elementos: "+tope);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnTxt = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnCopiar = new javax.swing.JButton();
        BtnPegar = new javax.swing.JButton();
        BtnPop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPila = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        BtnTxt.setBackground(new java.awt.Color(204, 255, 204));
        BtnTxt.setText("Insertar texto");
        BtnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTxtActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTxt);

        BtnEliminar.setBackground(new java.awt.Color(204, 255, 204));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar);

        BtnCopiar.setBackground(new java.awt.Color(204, 255, 204));
        BtnCopiar.setText("Copiar");
        BtnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCopiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCopiar);

        BtnPegar.setBackground(new java.awt.Color(204, 255, 204));
        BtnPegar.setText("Pegar");
        BtnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPegarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPegar);

        BtnPop.setBackground(new java.awt.Color(255, 204, 204));
        BtnPop.setText("Deshacer");
        BtnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPopActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPop);

        JPila.setEditable(false);
        JPila.setBackground(new java.awt.Color(219, 246, 245));
        JPila.setColumns(20);
        JPila.setRows(5);
        JPila.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(JPila);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1.setText("Pila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPopActionPerformed
        pop();
        verPila();
    }//GEN-LAST:event_BtnPopActionPerformed

    private void BtnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTxtActionPerformed
        push(BtnTxt.getText());
        verPila();
    }//GEN-LAST:event_BtnTxtActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        push(BtnEliminar.getText());
        verPila();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCopiarActionPerformed
        push(BtnCopiar.getText());
        verPila();
    }//GEN-LAST:event_BtnCopiarActionPerformed

    private void BtnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPegarActionPerformed
        push(BtnPegar.getText());
        verPila();
    }//GEN-LAST:event_BtnPegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pilas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCopiar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnPegar;
    private javax.swing.JButton BtnPop;
    private javax.swing.JButton BtnTxt;
    private javax.swing.JTextArea JPila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
